on:
  pull_request:
jobs:
  check_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: bar
        shell: bash
        run: |
          ls -halF
          git log --name-status HEAD^..HEAD
